-- One-time migration for the *existing* production D1 database (the
-- `agents` table already exists there, so schema.sql's
-- `CREATE TABLE IF NOT EXISTS` is a no-op on it -- this ALTER TABLE is the
-- only thing that actually adds the new column). A fresh `db:init:local` /
-- `db:init:remote` run against a brand-new database does NOT need this file;
-- schema.sql's CREATE TABLE already includes the column for that case.
--
-- MUST run before deploying any code (worker/src/agentService.ts's
-- setVerifierStatus, worker/src/verificationService.ts's
-- isAuthorizedVerifier check) that reads or writes this column -- deploying
-- first would make every request touching an agent record fail with a SQL
-- error ("no such column: is_authorized_verifier").
--
-- Run once, manually, against the real production database:
--   npx wrangler d1 execute inam-protocol-db --remote --file=./migration-add-verifier-status.sql
--
-- (For local dev, either re-run `npm run db:init:local` against a fresh
-- local D1 -- schema.sql already has the column -- or run this same file
-- with --local instead of --remote against an existing local database.)

ALTER TABLE agents ADD COLUMN is_authorized_verifier INTEGER NOT NULL DEFAULT 0;
