"""Cross-language correctness for ERC-8004 feedback (SPEC.md §11.1). The expected
file bytes and feedbackHash were generated by the TypeScript SDK (see
../../scripts/interop-vectors.ts, fixed test-only keys). Python must build the
identical file from the same receipt, or a feedbackHash computed on one side
would not match a file built on the other.
"""

import json

import pytest

from inamprotocol.client import InamApiError
from inamprotocol.erc8004 import build_erc8004_feedback, verify_erc8004_feedback

# --- Ground truth from `npx tsx scripts/interop-vectors.ts` (erc8004) ---
RECEIPT = json.loads("{\"receiptVersion\":\"1.0\",\"receiptId\":\"sha256:5e382e08630ea18c0ce803f5ea217a0e84c8e2258ef6aba0ed3bc9d7f4a070e4\",\"jobId\":\"job_interop_8004\",\"agentA\":{\"id\":\"did:key:z6Mkon3Necd6NkkyfoGoHxid2znGc59LU3K7mubaRcFbLfLX\",\"role\":\"requester\"},\"agentB\":{\"id\":\"did:key:z6Mko9hTggMwjSTEaJaPUfE6tqcy2xvU6BnNq3e3o8qVBiyH\",\"role\":\"worker\"},\"task\":{\"capability\":\"translation.tr-en\",\"specHash\":\"sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\",\"createdAt\":\"2026-10-01T10:00:00.000Z\"},\"result\":{\"outputHash\":\"sha256:bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb\",\"completedAt\":\"2026-10-01T10:05:00.000Z\"},\"settlement\":{\"amount\":\"12.50\",\"currency\":\"USDC\"},\"verification\":{\"method\":\"payer_confirmation\",\"outcome\":\"success\"},\"dispute\":{\"status\":\"none\",\"windowClosesAt\":\"2026-10-04T10:05:00.000Z\"},\"signatures\":{\"agentB\":\"Ue9QTeFxQoaRmNj0qiT9EzmOmOR5ntdPLSZMjH1KB2Q2p4ieCVrN4ObzxGkwqbYQ434o4txMYhztw+0IG4MVDg==\",\"agentA\":\"oSs7NGQ2lGU+F0fZyvGxdS9lWnRkE60jUdNjPblQIEUrv/KE+vHz8m9WNKuR7USHQVi2h7yjTushF5q3/PzbDw==\"},\"status\":\"finalized\",\"visibility\":\"public\"}")
EXPECTED_FILE_TEXT = "{\"agentId\":7,\"agentRegistry\":\"eip155:8453:0x0000000000000000000000000000000000008004\",\"clientAddress\":\"eip155:8453:0x1111111111111111111111111111111111111111\",\"createdAt\":\"2026-10-03T00:00:00.000Z\",\"inam\":{\"receipt\":{\"agentA\":{\"id\":\"did:key:z6Mkon3Necd6NkkyfoGoHxid2znGc59LU3K7mubaRcFbLfLX\",\"role\":\"requester\"},\"agentB\":{\"id\":\"did:key:z6Mko9hTggMwjSTEaJaPUfE6tqcy2xvU6BnNq3e3o8qVBiyH\",\"role\":\"worker\"},\"jobId\":\"job_interop_8004\",\"receiptId\":\"sha256:5e382e08630ea18c0ce803f5ea217a0e84c8e2258ef6aba0ed3bc9d7f4a070e4\",\"receiptVersion\":\"1.0\",\"result\":{\"completedAt\":\"2026-10-01T10:05:00.000Z\",\"outputHash\":\"sha256:bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb\"},\"settlement\":{\"amount\":\"12.50\",\"currency\":\"USDC\"},\"signatures\":{\"agentA\":\"oSs7NGQ2lGU+F0fZyvGxdS9lWnRkE60jUdNjPblQIEUrv/KE+vHz8m9WNKuR7USHQVi2h7yjTushF5q3/PzbDw==\",\"agentB\":\"Ue9QTeFxQoaRmNj0qiT9EzmOmOR5ntdPLSZMjH1KB2Q2p4ieCVrN4ObzxGkwqbYQ434o4txMYhztw+0IG4MVDg==\"},\"task\":{\"capability\":\"translation.tr-en\",\"createdAt\":\"2026-10-01T10:00:00.000Z\",\"specHash\":\"sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\"},\"verification\":{\"method\":\"payer_confirmation\",\"outcome\":\"success\"}}},\"tag1\":\"inam-receipt\",\"tag2\":\"translation.tr-en\",\"value\":100,\"valueDecimals\":0}"
EXPECTED_FEEDBACK_HASH = "0x0aeea54f4d752470a08f8771ca09d36245b9d1e2750b6096e8dee3ee40f8a882"

CLIENT = "0x1111111111111111111111111111111111111111"
PROVIDER_ADDR = "0x2222222222222222222222222222222222222222"
REGISTRY = "eip155:8453:0x0000000000000000000000000000000000008004"
REQUESTER = {"id": RECEIPT["agentA"]["id"], "linked": {"erc8004_id": CLIENT}}


class FakeRegistry:
    def __init__(self, receipt, requester_addr=CLIENT):
        self.receipt, self.requester_addr = receipt, requester_addr

    def get_agent(self, did):
        addr = self.requester_addr if did == RECEIPT["agentA"]["id"] else PROVIDER_ADDR
        return {"id": did, "linked": {"erc8004_id": addr}}

    def get_receipt(self, receipt_id):
        if receipt_id != self.receipt["receiptId"]:
            raise InamApiError("GET", "/v1/receipts", 404, {})
        return self.receipt


def test_python_builds_the_same_bytes_as_typescript():
    fb = build_erc8004_feedback(RECEIPT, REQUESTER, REGISTRY, 7, created_at="2026-10-03T00:00:00.000Z")
    assert fb["file_text"] == EXPECTED_FILE_TEXT
    assert fb["feedback_hash"] == EXPECTED_FEEDBACK_HASH
    assert fb["args"] == {"agentId": 7, "value": 100, "valueDecimals": 0, "tag1": "inam-receipt", "tag2": "translation.tr-en", "endpoint": "", "feedbackHash": EXPECTED_FEEDBACK_HASH}


def test_refuses_drafts_private_receipts_and_unlinked_requesters():
    with pytest.raises(ValueError, match="finalized"):
        build_erc8004_feedback({**RECEIPT, "status": "draft"}, REQUESTER, REGISTRY, 7)
    with pytest.raises(ValueError, match="participants_only"):
        build_erc8004_feedback({**RECEIPT, "visibility": "participants_only"}, REQUESTER, REGISTRY, 7)
    with pytest.raises(ValueError, match="erc8004_id"):
        build_erc8004_feedback(RECEIPT, {"id": RECEIPT["agentA"]["id"], "linked": {}}, REGISTRY, 7)


def test_python_verifies_a_typescript_built_file():
    check = verify_erc8004_feedback(EXPECTED_FILE_TEXT, EXPECTED_FEEDBACK_HASH, CLIENT, FakeRegistry(RECEIPT), value=100)
    assert check == {"valid": True, "reasons": [], "receipt_id": RECEIPT["receiptId"], "provider_did": RECEIPT["agentB"]["id"], "provider_address": PROVIDER_ADDR}


def test_rejects_replay_tampering_wrong_value_and_disputes():
    other = "0x3333333333333333333333333333333333333333"
    sybil = verify_erc8004_feedback(EXPECTED_FILE_TEXT, EXPECTED_FEEDBACK_HASH, other, FakeRegistry(RECEIPT))
    assert "feedback was not sent from the requester's proven erc8004_id" in sybil["reasons"]

    forged = EXPECTED_FILE_TEXT.replace('"outcome":"success"', '"outcome":"failed"')
    tampered = verify_erc8004_feedback(forged, EXPECTED_FEEDBACK_HASH, CLIENT, FakeRegistry(RECEIPT))
    assert {"feedbackHash does not match the file", "receiptId does not match the receipt content"} <= set(tampered["reasons"])

    wrong = verify_erc8004_feedback(EXPECTED_FILE_TEXT, EXPECTED_FEEDBACK_HASH, CLIENT, FakeRegistry(RECEIPT), value=0)
    assert wrong["reasons"] == ["value 0 does not match receipt outcome success"]

    disputed = verify_erc8004_feedback(EXPECTED_FILE_TEXT, EXPECTED_FEEDBACK_HASH, CLIENT, FakeRegistry({**RECEIPT, "status": "disputed"}))
    assert disputed["reasons"] == ["receipt is disputed in the registry"]
