"""x402 CounterpartyContext against the published vectors (x402 #1777),
generated by the TypeScript SDK (../../scripts/x402-context-vectors.ts). Each
vector's inputs are rebuilt from `presented` and `policy_input`, so this checks
normalization, canonical bytes, hash, decision and reason independently."""

import json
from pathlib import Path

import pytest

from inamprotocol.canonical import canonicalize
from inamprotocol.x402 import counterparty_context, x402_policy_input

VECTORS = json.loads(
    (Path(__file__).resolve().parents[2] / "tests" / "vectors" / "x402-counterparty-context.json").read_text(encoding="utf-8")
)


def _inputs(v):
    p = v["policy_input"]
    agent = {
        "id": p["counterparty_did"],
        "linked": {"erc8004_id": v["presented"]["bound_wallet"]},
        "revokedAt": "2026-10-01T00:00:00.000Z" if p["revoked"] else None,
    }
    reputation = {
        "evidenceLevel": p["evidence_level"],
        "trustScore": p["trust_score"],
        "flags": [],
        "evidence": {"freshness": {"evaluatedAt": p["trust_profile_issued_at"]}},
    }
    request = {
        "resource": p["requested_resource"],
        "amount": p["requested_amount"],
        "network": p["chain_or_settlement_network"],
        "nonce": p["nonce_or_request_id"],
    }
    policy = {"min_evidence": p["policy"]["minEvidence"], "min_trust_score": p["policy"]["minTrustScore"]}
    return agent, reputation, v["presented"]["pay_to"], request, policy


def test_vector_file_has_all_eight_cases():
    assert VECTORS["policy_version"] == "inam-x402-gate/1"
    assert len(VECTORS["vectors"]) == 8


@pytest.mark.parametrize("v", VECTORS["vectors"], ids=lambda v: v["name"])
def test_counterparty_context_matches_vector(v):
    agent, reputation, pay_to, request, policy = _inputs(v)
    policy_input = x402_policy_input(agent, reputation, pay_to, request, **policy)
    assert policy_input == v["policy_input"]
    assert canonicalize(policy_input, keep_null=True) == v["policy_input_canonical"]
    ctx = counterparty_context(agent, reputation, pay_to, request, **policy)
    assert ctx["policy_input_hash"] == v["context"]["policy_input_hash"]
    assert (ctx["decision"], ctx["reason"]) == (v["context"]["decision"], v["context"]["reason"])
    assert ctx == v["context"]


def test_missing_wallet_and_freshness_hash_as_json_null_like_js():
    agent = {"id": "did:key:z6MkagentEXAMPLE", "linked": {}}
    reputation = {"evidenceLevel": "countersigned", "trustScore": 40}
    request = {"resource": "r", "amount": "1", "network": "n", "nonce": "x"}
    canonical = canonicalize(x402_policy_input(agent, reputation, ["0xAB"], request), keep_null=True)
    assert '"bound_wallet":null' in canonical and '"trust_profile_issued_at":null' in canonical
    ctx = counterparty_context(agent, reputation, ["0xAB"], request)
    assert (ctx["decision"], ctx["counterparty_wallet_or_account"]) == ("deny", None)
